In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\BICT321 PROJECT\Books1.csv")
df = df.set_index('Book')
df

,Author(s),Original language,First published,Approximate sales,Genre
Book,,,,,
A Tale of Two Cities,Charles Dickens,English,1859,>200 million[20],Historical fiction
The Little Prince (Le Petit Prince),Antoine de Saint-Exupéry,French,1943,200 million[21][22][23],"Fantasy, children's fiction"
The Alchemist (O Alquimista),Paulo Coelho,Portuguese,1988,150 million[24][25],Fantasy
Harry Potter and the Philosopher's Stone,J. K. Rowling,English,1997,120 million[26][27],"Fantasy, children's fiction"
And Then There Were None,Agatha Christie,English,1939,100 million[28],Mystery
Dream of the Red Chamber (紅樓夢),Cao Xueqin,Chinese,1791,100 million[29][30],Family saga
The Hobbit,J. R. R. Tolkien,English,1937,100 million[31][32][33],"Fantasy, children's fiction"

In [3]:
df = df.drop_duplicates()
df

,Author(s),Original language,First published,Approximate sales,Genre
Book,,,,,
A Tale of Two Cities,Charles Dickens,English,1859,>200 million[20],Historical fiction
The Little Prince (Le Petit Prince),Antoine de Saint-Exupéry,French,1943,200 million[21][22][23],"Fantasy, children's fiction"
The Alchemist (O Alquimista),Paulo Coelho,Portuguese,1988,150 million[24][25],Fantasy
Harry Potter and the Philosopher's Stone,J. K. Rowling,English,1997,120 million[26][27],"Fantasy, children's fiction"
And Then There Were None,Agatha Christie,English,1939,100 million[28],Mystery
Dream of the Red Chamber (紅樓夢),Cao Xueqin,Chinese,1791,100 million[29][30],Family saga
The Hobbit,J. R. R. Tolkien,English,1937,100 million[31][32][33],"Fantasy, children's fiction"

In [6]:
df = df.drop(columns = "Genre")
df

,Author(s),Original language,First published,Approximate sales
Book,,,,
A Tale of Two Cities,Charles Dickens,English,1859,>200 million[20]
The Little Prince (Le Petit Prince),Antoine de Saint-Exupéry,French,1943,200 million[21][22][23]
The Alchemist (O Alquimista),Paulo Coelho,Portuguese,1988,150 million[24][25]
Harry Potter and the Philosopher's Stone,J. K. Rowling,English,1997,120 million[26][27]
And Then There Were None,Agatha Christie,English,1939,100 million[28]
Dream of the Red Chamber (紅樓夢),Cao Xueqin,Chinese,1791,100 million[29][30]
The Hobbit,J. R. R. Tolkien,English,1937,100 million[31][32][33]

In [9]:
df["Approximate sales"].str.lstrip(">")

Book
A Tale of Two Cities                                200 million[20]
The Little Prince (Le Petit Prince)         200 million[21][22][23]
The Alchemist (O Alquimista)                    150 million[24][25]
Harry Potter and the Philosopher's Stone        120 million[26][27]
And Then There Were None                            100 million[28]
Dream of the Red Chamber (紅樓夢)                  100 million[29][30]
The Hobbit                                  100 million[31][32][33]
Name: Approximate sales, dtype: object